server:
    port: 9000
    
spring:
    view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp

    messages:
        basename: i18n/messages

    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show_sql: true
        generate_dll: false # true | false
        
        hibernate:
            ddl-auto: none # none | create

application:
    dataSource:
        driverClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/sip07?autoReconnect=true
        username: root
        password: Accenture1

        initializer:
            enabled: true
            
            scripts:
                create: sql/create-schema.sql
                insert: sql/insert-data.sql
